### ISSUE TITLE
Refactor "Levels" to be more about the action than the object

### ISSUE THREAD

**Issue by steven-murray** [edges-collab/edges-analysis#109]
Currently our "levels" are these huge kind of objects that have associated methods, and inherit different things from each other. This has led to a lot of redundant code between them. It would actually make more sense for there to be a central unifying object that is able to capture all of the levels, and then have each method (flagging, averaging, etc.) be an external function that acts on one or more of these objects. This would make the creation of new methods much easier, and we wouldn't have to re-implement for each level.

**Comment by nmahesh1412** [comment]
Add feature to retain the meta data of all processes and filters done up until that point.
