### ISSUE TITLE
Balun and Connector Loss

### ISSUE THREAD

**Issue by steven-murray** [edges-collab/edges-analysis#9]
I'm currently getting weird results for the balun and connector loss functions. For mid-band I'm getting: 

![image](https://user-images.githubusercontent.com/1272030/79276480-f2928100-7e5c-11ea-8f3c-78d48b3fbbff.png)

This doesn't seem right. @gitul do you have a generic plot that I can compare to? I probably muffed something when cleaning up the function.

**Comment by gitul** [comment]
Hi Steven,

here is the plot for Mid-Band. Did you check if the antenna S11 that you have to enter as an input to the function looks OK ?

Cheers
Raul
________________________________

**Comment by steven-murray** [comment]
@gitul I think you may have attached the figure to an email -- but this is through Github, so it won't take attachments. If you go to the github issue itself you can copy and paste images.

**Comment by gitul** [comment]
OK, here is the figure.

@steven-murray your S11 magnitude looks strange. What are the units?  dB? 

![balun_connector](https://user-images.githubusercontent.com/44306838/79369608-3a79dc80-7f1f-11ea-93f6-4c29f663fc22.png)

**Comment by steven-murray** [comment]
Thanks @gitul! Yup that looks very different. My y-axis units are just log (base e). It looks (roughly) the same shape as the png output on enterprise along with the 4 input files. I will look into this further.

**Comment by steven-murray** [comment]
Fixed in a86e515
